import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Existing brand palette
        brand: {
          50: '#f0f7ff',
          100: '#e0effe',
          200: '#bae0fd',
          300: '#7cc7fb',
          400: '#36aaf6',
          500: '#0c8ee7',
          600: '#0270c5',
          700: '#0359a0',
          800: '#074c84',
          900: '#0c406e',
          950: '#082849',
        },
        // IcePanel Studio — Material Design 3 light-mode token palette
        'on-error-container': '#93000a',
        'on-secondary-container': '#fffbff',
        'on-surface': '#131b2e',
        'on-secondary-fixed-variant': '#2f2ebe',
        'surface-container': '#eaedff',
        'on-surface-variant': '#3f4850',
        'inverse-on-surface': '#eef0ff',
        'on-primary-fixed': '#001d31',
        'inverse-primary': '#93ccff',
        'outline-variant': '#bfc7d2',
        'surface': '#faf8ff',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#07006c',
        'outline': '#707881',
        'surface-dim': '#d2d9f4',
        'surface-container-highest': '#dae2fd',
        'background': '#faf8ff',
        'secondary-fixed': '#e1e0ff',
        'surface-tint': '#006398',
        'surface-container-low': '#f2f3ff',
        'on-background': '#131b2e',
        'surface-variant': '#dae2fd',
        'error': '#ba1a1a',
        'on-primary-container': '#fdfcff',
        'primary-container': '#007bb9',
        'tertiary-fixed-dim': '#4edea3',
        'inverse-surface': '#283044',
        'on-tertiary-container': '#f5fff6',
        'primary': '#006194',
        'tertiary': '#006947',
        'on-primary-fixed-variant': '#004b73',
        'on-secondary': '#ffffff',
        'surface-bright': '#faf8ff',
        'surface-container-high': '#e2e7ff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#93ccff',
        'primary-fixed': '#cce5ff',
        'secondary': '#4648d4',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-container': '#00855b',
        'on-tertiary-fixed-variant': '#005236',
        'secondary-fixed-dim': '#c0c1ff',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#6063ee',
        'on-tertiary-fixed': '#002113',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        'space-xl': '2rem',
        'space-xs': '0.25rem',
        'space-lg': '1.25rem',
        'space-md': '0.75rem',
        'gutter': '1rem',
        'margin': '1.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'mono-code': ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};

export default config;
