/**
 * Architecture & Flow Definitions from IcePanel's:
 * "Reimagining UML sequence diagrams in IcePanel"
 * https://icepanel.io/blog/reimagining-uml-sequence-diagrams-in-icepanel
 *
 * Contains:
 * 1. Online Boutique Container/App Model (Level 2 Apps & Stores)
 * 2. Online Boutique System Context Model (Level 1 Customer Purchase Context)
 * 3. Simple UML Sequence Model (Computer <-> Server 6-step flow)
 * 4. The 27-Step "User purchase flows" with alt paths: [Success], [Failed], [Timeout]
 * 5. The 9-Step "User see's adverts" flow
 * 6. Visual graph helpers for Canvas and Share Link projections
 */

import type { CanvasEdge, CanvasNode } from './canvas';
import type { ArchitectureId, ConnectionId, FlowId, ObjectId, VersionId, ViewId } from './ids';
import type { FlowStep, FlowWithSteps, ModelConnection, ModelObject, View } from './types';

// ─── Online Boutique App Level Objects & Connections ────────────────────────

export interface IcePanelBoutiqueData {
  objects: ModelObject[];
  connections: ModelConnection[];
  nodes: CanvasNode[];
  edges: CanvasEdge[];
  flows: FlowWithSteps[];
  views: View[];
}

export function createIcePanelBoutiqueModel(): IcePanelBoutiqueData {
  const archId = 'arch-icepanel-boutique' as ArchitectureId;
  const verId = 'v1' as VersionId;

  // 1. Model Objects
  const objects: ModelObject[] = [
    {
      id: 'obj-customers' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'actor',
      name: 'Customers',
      description: 'End customers browsing online boutique and purchasing products.',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-load-generator' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'actor',
      name: 'Load Generator',
      description: 'Synthetic traffic generator simulating continuous checkout workflows.',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-frontend' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'application',
      name: 'Frontend',
      description: 'Exposes an HTTP server to serve the website.',
      metadata: { technology: 'Go / HTTP' },
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-cart-service' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'application',
      name: 'Cart Service',
      description: "Stores the items in the user's shopping cart in Redis and retrieves it.",
      metadata: { technology: 'C# / gRPC' },
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-cart-cache' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'store',
      name: 'Cart Cache',
      description: 'Store items added to cart.',
      metadata: { technology: 'Redis' },
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-checkout-service' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'application',
      name: 'Checkout Service',
      description:
        'Retrieves user cart, prepares orders and orchestrates the payment, shipping and the email notification.',
      metadata: { technology: 'Go / gRPC' },
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-email-service' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'application',
      name: 'Email Service',
      description: 'Sends users an order confirmation email.',
      metadata: { technology: 'Python / gRPC' },
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-payment-service' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'application',
      name: 'Payment Service',
      description:
        'Charges the given credit card info with the given amount and returns a transaction ID.',
      metadata: { technology: 'Node.js / gRPC' },
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-shipping-service' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'application',
      name: 'Shipping Service',
      description:
        'Gives shipping cost estimates based on the shopping cart. Ships items to the given address.',
      metadata: { technology: 'Go / gRPC' },
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-product-catalogue-service' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'application',
      name: 'Product Catalogue Service',
      description:
        'Provides the list of products from a JSON file and ability to search products and get individual products.',
      metadata: { technology: 'Go / gRPC' },
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-currency-service' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'application',
      name: 'Currency Service',
      description: 'Converts one money amount to another currency.',
      metadata: { technology: 'Node.js / gRPC' },
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-ad-service' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'application',
      name: 'Ad Service',
      description: 'Provides text ads based on given context words.',
      metadata: { technology: 'Java / gRPC' },
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-recommendation-service' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'application',
      name: 'Recommendation Service',
      description: 'Recommends other products based on what is given in the cart.',
      metadata: { technology: 'Python / gRPC' },
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-currency-api' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'application',
      name: 'Currency Exchange API',
      description: 'European Central Bank public exchange rates API.',
      metadata: { technology: 'REST HTTPS' },
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-payment-gateway' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'system',
      name: 'Payment Gateway',
      description: 'External card payment clearing gateway.',
      metadata: { technology: 'WebSocket mTLS' },
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
  ];

  // 2. Model Connections
  const connections: ModelConnection[] = [
    {
      id: 'conn-cust-self' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-customers' as ObjectId,
      targetObjectId: 'obj-customers' as ObjectId,
      kind: 'sync',
      label: 'clicks checkout',
      description: 'User clicks checkout and pay',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-cust-front' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-customers' as ObjectId,
      targetObjectId: 'obj-frontend' as ObjectId,
      kind: 'sync',
      label: 'Real user traffic',
      description: 'User requests to make a purchase via Real user traffic',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-front-cust' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-frontend' as ObjectId,
      targetObjectId: 'obj-customers' as ObjectId,
      kind: 'sync',
      label: 'Confirm purchase',
      description: 'Confirm user purchase via Real user traffic',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-load-front' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-load-generator' as ObjectId,
      targetObjectId: 'obj-frontend' as ObjectId,
      kind: 'sync',
      label: 'Continuous requests',
      description: 'Sends continuous requests to',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-front-checkout' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-frontend' as ObjectId,
      targetObjectId: 'obj-checkout-service' as ObjectId,
      kind: 'sync',
      label: 'Start checkout process',
      description: 'Initiate checkout process via Start checkout process for product',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-checkout-front' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-checkout-service' as ObjectId,
      targetObjectId: 'obj-frontend' as ObjectId,
      kind: 'sync',
      label: 'Confirmation message',
      description: 'Payment and order confirmation message via Start checkout process for product',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-checkout-catalog' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-checkout-service' as ObjectId,
      targetObjectId: 'obj-product-catalogue-service' as ObjectId,
      kind: 'sync',
      label: 'Request price & stock',
      description: 'Check products are in stock and reserve via Request price of product',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-catalog-checkout' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-product-catalogue-service' as ObjectId,
      targetObjectId: 'obj-checkout-service' as ObjectId,
      kind: 'sync',
      label: 'Reservation confirmed',
      description: 'Send confirmation of reservation via Request price of product',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-checkout-cart' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-checkout-service' as ObjectId,
      targetObjectId: 'obj-cart-service' as ObjectId,
      kind: 'sync',
      label: 'Get cart details',
      description: "Fetches the users cart details via Get's in stock items in cart from",
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-cart-checkout' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-cart-service' as ObjectId,
      targetObjectId: 'obj-checkout-service' as ObjectId,
      kind: 'sync',
      label: 'Return cart items',
      description: "Returns cached items via Get's in stock items in cart from",
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-cart-cache' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-cart-service' as ObjectId,
      targetObjectId: 'obj-cart-cache' as ObjectId,
      kind: 'sync',
      label: 'Check Redis cache',
      description: 'Checks user cached cart via Checks items from',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-cache-cart' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-cart-cache' as ObjectId,
      targetObjectId: 'obj-cart-service' as ObjectId,
      kind: 'sync',
      label: 'Return cached data',
      description: 'Returns cached items via Checks items from',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-checkout-shipping' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-checkout-service' as ObjectId,
      targetObjectId: 'obj-shipping-service' as ObjectId,
      kind: 'sync',
      label: 'Shipping instructions',
      description: 'Get shipping details via Send shipping instructions',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-shipping-checkout' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-shipping-service' as ObjectId,
      targetObjectId: 'obj-checkout-service' as ObjectId,
      kind: 'sync',
      label: 'Shipping quote',
      description: 'Returns shipping details via Send shipping instructions',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-checkout-payment' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-checkout-service' as ObjectId,
      targetObjectId: 'obj-payment-service' as ObjectId,
      kind: 'sync',
      label: 'Process payment',
      description: 'Send payment to process via Make payment after checkout',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-payment-checkout' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-payment-service' as ObjectId,
      targetObjectId: 'obj-checkout-service' as ObjectId,
      kind: 'sync',
      label: 'Payment confirmation',
      description: 'Payment confirmation via Make payment after checkout',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-payment-currency' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-payment-service' as ObjectId,
      targetObjectId: 'obj-currency-api' as ObjectId,
      kind: 'sync',
      label: 'Fetch exchange rate',
      description:
        'Fetch currency exchange of local currency via Fetch latest exchange rate for payment',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-currency-payment' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-currency-api' as ObjectId,
      targetObjectId: 'obj-payment-service' as ObjectId,
      kind: 'sync',
      label: 'Return exchange rate',
      description: 'Return exchange rate via Fetch latest exchange rate for payment',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-checkout-email' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-checkout-service' as ObjectId,
      targetObjectId: 'obj-email-service' as ObjectId,
      kind: 'async',
      label: 'Order confirmation',
      description:
        'Create automated email confirmation to customer via Confirm order has been placed',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-email-cust' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-email-service' as ObjectId,
      targetObjectId: 'obj-customers' as ObjectId,
      kind: 'async',
      label: 'Send confirmation email',
      description: 'Send confirmation email via Email',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-payment-gateway' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-payment-service' as ObjectId,
      targetObjectId: 'obj-payment-gateway' as ObjectId,
      kind: 'sync',
      label: 'Create card transactions',
      description: 'Payment clearing transactions',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-payment-self' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-payment-service' as ObjectId,
      targetObjectId: 'obj-payment-service' as ObjectId,
      kind: 'sync',
      label: 'Timeout & retry',
      description: 'Payment timeout (2 mins) and retry payment',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-front-ad' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-frontend' as ObjectId,
      targetObjectId: 'obj-ad-service' as ObjectId,
      kind: 'sync',
      label: 'Fetch relevant ads',
      description: 'Fetches relevant ads from Ad Service',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-front-rec' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-frontend' as ObjectId,
      targetObjectId: 'obj-recommendation-service' as ObjectId,
      kind: 'sync',
      label: 'Get recommendations',
      description: 'Get recommended items based on cart',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-front-currency' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-frontend' as ObjectId,
      targetObjectId: 'obj-currency-service' as ObjectId,
      kind: 'sync',
      label: 'Get quote for currency',
      description: 'Get quote for currency conversion',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
  ];

  // 3. Canvas Nodes matching IcePanel diagram layout
  const nodes: CanvasNode[] = [
    {
      id: 'obj-customers',
      type: 'person',
      position: { x: 580, y: 40 },
      data: {
        label: 'Customers',
        kind: 'actor',
        icon: 'person',
        description: 'User clicks checkout and pay',
        badge: 'Actor',
        color: '#ba1a1a',
      },
    },
    {
      id: 'obj-load-generator',
      type: 'person',
      position: { x: 860, y: 40 },
      data: {
        label: 'Load Generator',
        kind: 'actor',
        icon: 'person',
        description: 'Sends continuous requests to',
        badge: 'Actor',
        color: '#ba1a1a',
      },
    },
    {
      id: 'obj-frontend',
      type: 'app',
      position: { x: 560, y: 320 },
      data: {
        label: 'Frontend',
        kind: 'application',
        icon: 'desktop_windows',
        description: 'Exposes an HTTP server to serve the website',
        badge: 'App Service',
        metadata: { technology: 'Go / HTTP' },
        color: '#006194',
      },
    },
    {
      id: 'obj-cart-service',
      type: 'app',
      position: { x: 260, y: 150 },
      data: {
        label: 'Cart Service',
        kind: 'application',
        icon: 'shopping_cart',
        description: "Stores the items in the user's shopping cart in Redis and retrieves it.",
        badge: 'App Service',
        metadata: { technology: 'C# / gRPC' },
        color: '#4648d4',
      },
    },
    {
      id: 'obj-cart-cache',
      type: 'database',
      position: { x: 480, y: 150 },
      data: {
        label: 'Cart Cache',
        kind: 'store',
        icon: 'database',
        description: 'Store items added to cart.',
        badge: 'Data Store',
        metadata: { technology: 'Redis' },
        color: '#006947',
      },
    },
    {
      id: 'obj-checkout-service',
      type: 'app',
      position: { x: 240, y: 340 },
      data: {
        label: 'Checkout Service',
        kind: 'application',
        icon: 'payment',
        description:
          'Retrieves user cart, prepares orders and orchestrates payment, shipping, and email.',
        badge: 'App Service',
        metadata: { technology: 'Go / gRPC' },
        color: '#4648d4',
      },
    },
    {
      id: 'obj-email-service',
      type: 'app',
      position: { x: 40, y: 150 },
      data: {
        label: 'Email Service',
        kind: 'application',
        icon: 'mail',
        description: 'Sends users an order confirmation email.',
        badge: 'App Service',
        metadata: { technology: 'Python / gRPC' },
        color: '#4648d4',
      },
    },
    {
      id: 'obj-payment-service',
      type: 'app',
      position: { x: 40, y: 560 },
      data: {
        label: 'Payment Service',
        kind: 'application',
        icon: 'credit_card',
        description: 'Charges given credit card and returns transaction ID.',
        badge: 'App Service',
        metadata: { technology: 'Node.js / gRPC' },
        color: '#4648d4',
      },
    },
    {
      id: 'obj-shipping-service',
      type: 'app',
      position: { x: 240, y: 560 },
      data: {
        label: 'Shipping Service',
        kind: 'application',
        icon: 'local_shipping',
        description: 'Gives shipping estimates and ships items to given address.',
        badge: 'App Service',
        metadata: { technology: 'Go / gRPC' },
        color: '#4648d4',
      },
    },
    {
      id: 'obj-product-catalogue-service',
      type: 'app',
      position: { x: 440, y: 590 },
      data: {
        label: 'Product Catalogue Service',
        kind: 'application',
        icon: 'inventory',
        description: 'Provides product list and search capabilities.',
        badge: 'App Service',
        metadata: { technology: 'Go / gRPC' },
        color: '#4648d4',
      },
    },
    {
      id: 'obj-currency-service',
      type: 'app',
      position: { x: 620, y: 500 },
      data: {
        label: 'Currency Service',
        kind: 'application',
        icon: 'currency_exchange',
        description: 'Converts money amount to target currency.',
        badge: 'App Service',
        metadata: { technology: 'Node.js / gRPC' },
        color: '#4648d4',
      },
    },
    {
      id: 'obj-ad-service',
      type: 'app',
      position: { x: 880, y: 220 },
      data: {
        label: 'Ad Service',
        kind: 'application',
        icon: 'campaign',
        description: 'Provides text ads based on context words.',
        badge: 'App Service',
        metadata: { technology: 'Java / gRPC' },
        color: '#4648d4',
      },
    },
    {
      id: 'obj-recommendation-service',
      type: 'app',
      position: { x: 880, y: 440 },
      data: {
        label: 'Recommendation Service',
        kind: 'application',
        icon: 'recommend',
        description: 'Recommends products based on user cart contents.',
        badge: 'App Service',
        metadata: { technology: 'Python / gRPC' },
        color: '#4648d4',
      },
    },
    {
      id: 'obj-currency-api',
      type: 'external',
      position: { x: 620, y: 720 },
      data: {
        label: 'Currency Exchange API',
        kind: 'application',
        icon: 'account_balance',
        description: 'European Central Bank public exchange rate feed.',
        badge: 'External App',
        metadata: { technology: 'REST HTTPS' },
        color: '#707881',
      },
    },
    {
      id: 'obj-payment-gateway',
      type: 'external',
      position: { x: 40, y: 720 },
      data: {
        label: 'Payment Gateway',
        kind: 'system',
        icon: 'payments',
        description: 'External card transaction processing gateway.',
        badge: 'External System',
        metadata: { technology: 'WebSocket mTLS' },
        color: '#707881',
      },
    },
  ];

  // 4. Canvas Edges
  const edges: CanvasEdge[] = [
    {
      id: 'edge-cust-front',
      source: 'obj-customers',
      target: 'obj-frontend',
      label: 'Real user traffic',
      data: { protocol: 'HTTP : 80', kind: 'sync' },
    },
    {
      id: 'edge-load-front',
      source: 'obj-load-generator',
      target: 'obj-frontend',
      label: 'Continuous requests',
      data: { protocol: 'HTTP', kind: 'sync' },
    },
    {
      id: 'edge-front-checkout',
      source: 'obj-frontend',
      target: 'obj-checkout-service',
      label: 'Initiate checkout process',
      data: { protocol: 'gRPC', kind: 'sync' },
    },
    {
      id: 'edge-checkout-catalog',
      source: 'obj-checkout-service',
      target: 'obj-product-catalogue-service',
      label: 'Check stock & reserve',
      data: { protocol: 'gRPC', kind: 'sync' },
    },
    {
      id: 'edge-checkout-cart',
      source: 'obj-checkout-service',
      target: 'obj-cart-service',
      label: 'Get user cart details',
      data: { protocol: 'gRPC', kind: 'sync' },
    },
    {
      id: 'edge-cart-cache',
      source: 'obj-cart-service',
      target: 'obj-cart-cache',
      label: 'Check user cached cart',
      data: { protocol: 'TCP 6379', kind: 'sync' },
    },
    {
      id: 'edge-checkout-shipping',
      source: 'obj-checkout-service',
      target: 'obj-shipping-service',
      label: 'Get shipping details',
      data: { protocol: 'gRPC', kind: 'sync' },
    },
    {
      id: 'edge-checkout-payment',
      source: 'obj-checkout-service',
      target: 'obj-payment-service',
      label: 'Make payment after checkout',
      data: { protocol: 'gRPC', kind: 'sync' },
    },
    {
      id: 'edge-payment-currency',
      source: 'obj-payment-service',
      target: 'obj-currency-api',
      label: 'Fetch exchange rate',
      data: { protocol: 'REST HTTPS', kind: 'sync' },
    },
    {
      id: 'edge-payment-gateway',
      source: 'obj-payment-service',
      target: 'obj-payment-gateway',
      label: 'Create card transactions',
      data: { protocol: 'WebSocket', kind: 'sync' },
    },
    {
      id: 'edge-checkout-email',
      source: 'obj-checkout-service',
      target: 'obj-email-service',
      label: 'Confirm order placed',
      data: { protocol: 'gRPC', kind: 'async' },
    },
    {
      id: 'edge-email-cust',
      source: 'obj-email-service',
      target: 'obj-customers',
      label: 'Send confirmation email',
      data: { protocol: 'SMTP', kind: 'async' },
    },
    {
      id: 'edge-front-ad',
      source: 'obj-frontend',
      target: 'obj-ad-service',
      label: 'Fetches relevant ads',
      data: { protocol: 'gRPC', kind: 'sync' },
    },
    {
      id: 'edge-front-rec',
      source: 'obj-frontend',
      target: 'obj-recommendation-service',
      label: 'Get recommendations',
      data: { protocol: 'gRPC', kind: 'sync' },
    },
    {
      id: 'edge-front-currency',
      source: 'obj-frontend',
      target: 'obj-currency-service',
      label: 'Get currency quote',
      data: { protocol: 'gRPC', kind: 'sync' },
    },
  ];

  // 5. The 27-Step "User purchase flows" Flow Sequence
  const purchaseSteps: FlowStep[] = [
    {
      id: 'step-1',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-cust-self' as ConnectionId,
      stepIndex: 0,
      note: 'User clicks checkout and pay',
      actorAction: 'Clicks Checkout & Pay button',
      userIntent: 'Complete shopping basket checkout',
    },
    {
      id: 'step-2',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-cust-front' as ConnectionId,
      stepIndex: 1,
      note: 'User requests to make a purchase via Real user traffic',
      actorAction: 'Submits order request',
      endpoint: '/api/checkout',
      httpMethod: 'POST',
      statusCode: 200,
    },
    {
      id: 'step-3',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-front-checkout' as ConnectionId,
      stepIndex: 2,
      note: 'Initiate checkout process via Start checkout process for product',
      endpoint: 'hipstershop.CheckoutService/PlaceOrder',
      httpMethod: 'gRPC',
    },
    {
      id: 'step-4',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-checkout-catalog' as ConnectionId,
      stepIndex: 3,
      note: 'Check products are in stock and reserve via Request price of product',
      endpoint: 'hipstershop.ProductCatalogService/GetProduct',
      httpMethod: 'gRPC',
    },
    {
      id: 'step-5',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-catalog-checkout' as ConnectionId,
      stepIndex: 4,
      note: 'Send confirmation of reservation via Request price of product',
      statusCode: 200,
    },
    {
      id: 'step-6',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-checkout-cart' as ConnectionId,
      stepIndex: 5,
      note: "Fetches the users cart details via Get's in stock items in cart from",
      endpoint: 'hipstershop.CartService/GetCart',
      httpMethod: 'gRPC',
    },
    {
      id: 'step-7',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-cart-cache' as ConnectionId,
      stepIndex: 6,
      note: 'Checks user cached cart via Checks items from',
      endpoint: 'HGETALL cart:{userId}',
      httpMethod: 'TCP',
    },
    {
      id: 'step-8',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-cache-cart' as ConnectionId,
      stepIndex: 7,
      note: 'Returns cached items via Checks items from',
      statusCode: 200,
    },
    {
      id: 'step-9',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-cart-checkout' as ConnectionId,
      stepIndex: 8,
      note: "Returns cached items via Get's in stock items in cart from",
      statusCode: 200,
    },
    {
      id: 'step-10',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-checkout-shipping' as ConnectionId,
      stepIndex: 9,
      note: 'Get shipping details via Send shipping instructions',
      endpoint: 'hipstershop.ShippingService/GetQuote',
      httpMethod: 'gRPC',
    },
    {
      id: 'step-11',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-shipping-checkout' as ConnectionId,
      stepIndex: 10,
      note: 'Returns shipping details via Send shipping instructions',
      statusCode: 200,
    },
    {
      id: 'step-12',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-checkout-payment' as ConnectionId,
      stepIndex: 11,
      note: 'Send payment to process via Make payment after checkout',
      endpoint: 'hipstershop.PaymentService/Charge',
      httpMethod: 'gRPC',
    },
    {
      id: 'step-13',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-payment-currency' as ConnectionId,
      stepIndex: 12,
      note: 'Fetch currency exchange of local currency via Fetch latest exchange rate for payment',
      endpoint: 'GET /latest?base=USD',
      httpMethod: 'HTTPS',
    },
    {
      id: 'step-14',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-currency-payment' as ConnectionId,
      stepIndex: 13,
      note: 'Return exchange rate via Fetch latest exchange rate for payment',
      statusCode: 200,
    },
    // Alt branch: [Success]
    {
      id: 'step-15',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-payment-checkout' as ConnectionId,
      stepIndex: 14,
      note: '[Success] Payment confirmation via Make payment after checkout',
      statusCode: 200,
    },
    {
      id: 'step-16',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-checkout-email' as ConnectionId,
      stepIndex: 15,
      note: '[Success] Create automated email confirmation to customer via Confirm order has been placed',
      endpoint: 'hipstershop.EmailService/SendOrderConfirmation',
      httpMethod: 'gRPC',
    },
    {
      id: 'step-17',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-email-cust' as ConnectionId,
      stepIndex: 16,
      note: '[Success] Send confirmation email via Email',
      actorAction: 'Delivers receipt to customer inbox',
    },
    {
      id: 'step-18',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-checkout-front' as ConnectionId,
      stepIndex: 17,
      note: '[Success] Payment and order confirmation message via Start checkout process for product',
      statusCode: 200,
    },
    {
      id: 'step-19',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-front-cust' as ConnectionId,
      stepIndex: 18,
      note: '[Success] Confirm user purchase via Real user traffic',
      statusCode: 200,
      actorAction: 'Displays Order Success confirmation page',
    },
    // Alt branch: [Failed]
    {
      id: 'step-20',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-payment-checkout' as ConnectionId,
      stepIndex: 19,
      note: '[Failed] Payment unsuccessful message via Make payment after checkout',
      statusCode: 402,
    },
    {
      id: 'step-21',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-checkout-front' as ConnectionId,
      stepIndex: 20,
      note: '[Failed] Payment failed via Start checkout process for product',
      statusCode: 402,
    },
    {
      id: 'step-22',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-front-cust' as ConnectionId,
      stepIndex: 21,
      note: '[Failed] Payment unsuccessful message via Real user traffic',
      statusCode: 402,
      actorAction: 'Displays payment declined notification and prompts retry',
    },
    // Alt branch: [Timeout]
    {
      id: 'step-23',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-payment-self' as ConnectionId,
      stepIndex: 22,
      note: '[Timeout] Payment timeout (2 mins)',
      statusCode: 504,
    },
    {
      id: 'step-24',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-payment-self' as ConnectionId,
      stepIndex: 23,
      note: '[Timeout] Retry payment gateway transaction',
    },
    {
      id: 'step-25',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-payment-checkout' as ConnectionId,
      stepIndex: 24,
      note: '[Timeout] Payment timeout via Make payment after checkout',
      statusCode: 504,
    },
    {
      id: 'step-26',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-checkout-front' as ConnectionId,
      stepIndex: 25,
      note: '[Timeout] Payment timeout via Start checkout process for product',
      statusCode: 504,
    },
    {
      id: 'step-27',
      flowId: 'flow-user-purchase' as FlowId,
      connectionId: 'conn-front-cust' as ConnectionId,
      stepIndex: 26,
      note: '[Timeout] Payment timeout via Real user traffic',
      statusCode: 504,
      actorAction: 'Notifies customer of payment processing delay and status check',
    },
  ];

  const userPurchaseFlow: FlowWithSteps = {
    id: 'flow-user-purchase' as FlowId,
    architectureId: archId,
    name: 'User purchase flows',
    description:
      'Complete 27-step purchase sequence with alternate success, failed, and timeout branches as depicted in IcePanel.',
    type: 'user_journey',
    actorId: 'obj-customers' as ObjectId,
    persona: 'Customer',
    steps: purchaseSteps,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  };

  // 6. The 9-Step "User see's adverts" Flow Sequence
  const advertsSteps: FlowStep[] = [
    {
      id: 'adv-1',
      flowId: 'flow-user-adverts' as FlowId,
      connectionId: 'conn-cust-front' as ConnectionId,
      stepIndex: 0,
      note: 'User navigates to store catalogue page',
      actorAction: 'Browses product items',
    },
    {
      id: 'adv-2',
      flowId: 'flow-user-adverts' as FlowId,
      connectionId: 'conn-front-ad' as ConnectionId,
      stepIndex: 1,
      note: 'Fetches relevant ads from Ad Service',
      endpoint: 'hipstershop.AdService/GetAds',
      httpMethod: 'gRPC',
    },
    {
      id: 'adv-3',
      flowId: 'flow-user-adverts' as FlowId,
      connectionId: 'conn-front-ad' as ConnectionId,
      stepIndex: 2,
      note: 'Context keyword matcher ranks applicable banner ads',
    },
    {
      id: 'adv-4',
      flowId: 'flow-user-adverts' as FlowId,
      connectionId: 'conn-front-ad' as ConnectionId,
      stepIndex: 3,
      note: 'Returns targeted advertisement payloads',
      statusCode: 200,
    },
    {
      id: 'adv-5',
      flowId: 'flow-user-adverts' as FlowId,
      connectionId: 'conn-front-rec' as ConnectionId,
      stepIndex: 4,
      note: 'Get recommended items for customer session',
      endpoint: 'hipstershop.RecommendationService/ListRecommendations',
      httpMethod: 'gRPC',
    },
    {
      id: 'adv-6',
      flowId: 'flow-user-adverts' as FlowId,
      connectionId: 'conn-front-rec' as ConnectionId,
      stepIndex: 5,
      note: 'Calculates product similarity matrix',
    },
    {
      id: 'adv-7',
      flowId: 'flow-user-adverts' as FlowId,
      connectionId: 'conn-front-rec' as ConnectionId,
      stepIndex: 6,
      note: 'Returns 4 recommended product IDs',
      statusCode: 200,
    },
    {
      id: 'adv-8',
      flowId: 'flow-user-adverts' as FlowId,
      connectionId: 'conn-front-currency' as ConnectionId,
      stepIndex: 7,
      note: 'Get quote for currency conversion',
      endpoint: 'hipstershop.CurrencyService/Convert',
      httpMethod: 'gRPC',
    },
    {
      id: 'adv-9',
      flowId: 'flow-user-adverts' as FlowId,
      connectionId: 'conn-front-currency' as ConnectionId,
      stepIndex: 8,
      note: 'Returns prices converted to local currency',
      statusCode: 200,
    },
  ];

  const userAdvertsFlow: FlowWithSteps = {
    id: 'flow-user-adverts' as FlowId,
    architectureId: archId,
    name: "User see's adverts",
    description:
      '9-step flow retrieving targeted ads, personalized recommendations, and localized currency rates.',
    type: 'user_journey',
    actorId: 'obj-customers' as ObjectId,
    persona: 'Customer',
    steps: advertsSteps,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  };

  const views: View[] = [
    {
      id: 'view-boutique-apps' as ViewId,
      architectureId: archId,
      name: 'Apps and stores (Online Boutique)',
      kind: 'container',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
  ];

  return {
    objects,
    connections,
    nodes,
    edges,
    flows: [userPurchaseFlow, userAdvertsFlow],
    views,
  };
}

/**
 * Returns the Simple UML Sequence Model (Computer <-> Server 6-step flow)
 * from https://assets.icepanel.io/blog/reimagining-uml-sequence-diagrams-in-icepanel/simple-sequence-diagrams.png
 */
export function createSimpleUmlSequenceModel(): {
  objects: ModelObject[];
  connections: ModelConnection[];
  flow: FlowWithSteps;
} {
  const archId = 'arch-simple-seq' as ArchitectureId;
  const verId = 'v1' as VersionId;

  const objects: ModelObject[] = [
    {
      id: 'obj-computer' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'application',
      name: ':Computer',
      description: 'Client computer running mail user agent',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'obj-server' as ObjectId,
      architectureId: archId,
      versionId: verId,
      kind: 'system',
      name: ':Server',
      description: 'Mail server providing IMAP / SMTP operations',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
  ];

  const connections: ModelConnection[] = [
    {
      id: 'conn-client-server' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-computer' as ObjectId,
      targetObjectId: 'obj-server' as ObjectId,
      kind: 'sync',
      label: 'email protocol',
      description: 'Computer to mail server message exchanges',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
    {
      id: 'conn-server-client' as ConnectionId,
      architectureId: archId,
      versionId: verId,
      sourceObjectId: 'obj-server' as ObjectId,
      targetObjectId: 'obj-computer' as ObjectId,
      kind: 'sync',
      label: 'response',
      description: 'Server return status',
      createdAt: new Date('2026-01-01'),
      updatedAt: new Date('2026-01-01'),
    },
  ];

  const flow: FlowWithSteps = {
    id: 'flow-simple-mail' as FlowId,
    architectureId: archId,
    name: 'Simple Mail Check Flow',
    description:
      'Simple UML Sequence diagram illustrating checkEmail, sendUnsentEmail, newEmail, response, and downloadEmail.',
    type: 'sequence',
    steps: [
      {
        id: 'step-sm-1',
        flowId: 'flow-simple-mail' as FlowId,
        connectionId: 'conn-client-server' as ConnectionId,
        stepIndex: 0,
        note: 'checkEmail',
      },
      {
        id: 'step-sm-2',
        flowId: 'flow-simple-mail' as FlowId,
        connectionId: 'conn-client-server' as ConnectionId,
        stepIndex: 1,
        note: 'sendUnsentEmail',
      },
      {
        id: 'step-sm-3',
        flowId: 'flow-simple-mail' as FlowId,
        connectionId: 'conn-client-server' as ConnectionId,
        stepIndex: 2,
        note: 'newEmail',
      },
      {
        id: 'step-sm-4',
        flowId: 'flow-simple-mail' as FlowId,
        connectionId: 'conn-server-client' as ConnectionId,
        stepIndex: 3,
        note: 'response',
      },
      {
        id: 'step-sm-5',
        flowId: 'flow-simple-mail' as FlowId,
        connectionId: 'conn-client-server' as ConnectionId,
        stepIndex: 4,
        note: '[newEmail] downloadEmail',
      },
      {
        id: 'step-sm-6',
        flowId: 'flow-simple-mail' as FlowId,
        connectionId: 'conn-client-server' as ConnectionId,
        stepIndex: 5,
        note: 'deleteOldEmail',
      },
    ],
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  };

  return { objects, connections, flow };
}
